name: Perform Maven Release (Standalone)

on:
  push:
    branches:
      - "INFRA-8096"
  #workflow_dispatch:

permissions:
  contents: write

env:
  JAVA_VERSION: '11' #(8, 11, 17, 21)

jobs:
  maven-release:
    name: Maven Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Set up JDK & GPG / Sonatype Settings
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: ${{ secrets.SONATYPE_USERNAME }}
          server-password: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Verify GPG Key & Passphrase (Clean Global Import)
        run: |
            unset GNUPGHOME
            mkdir -p ~/.gnupg
            chmod 700 ~/.gnupg
            
            echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
            echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
            gpgconf --kill gpg-agent
            
            echo "$RAW_GPG_KEY" > private.key
            gpg --batch --import private.key
            rm private.key
            
            mvn clean verify -B -ntp \
              -DskipTests=true \
              -Dmaven.javadoc.skip=true \
              -Dgpg.passphrase="$GPG_PASSPHRASE" \
              -Dgpg.keyname="95BCB1665C76C3A6"
        env:
            RAW_GPG_KEY: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}

#      - name: Run Maven Release
#        run: |
#          mvn -B -ntp \
#            -Darguments="-Dmaven.javadoc.skip=true -DskipTests=true -DaltReleaseDeploymentRepository=releases::default::gs://airship-maven-artifacts/releases -DaltDeploymentRepository=releases::default::gs://airship-maven-artifacts/releases" \
#            -Dresume=false \
#            -DscmCommentPrefix="[github] [skip ci] " \
#            -DtagNameFormat=@{project.version} \
#            -DpushChanges=false \
#            -DlocalCheckout=true \
#            release:prepare release:perform
#        env:
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

#      - name: Push Changes & Tags
#        if: success()
#        run: |
#          git push origin master
#          git push origin --tags